/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mirzayogy.bangsukri_5c.frames.barangmasuk;

import com.mirzayogy.bangsukri_5c.db.Basisdata;
import com.mirzayogy.bangsukri_5c.libraries.ComboBoxItem;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author mirza
 */
public class BarangMasukAddFrame extends javax.swing.JFrame {

    /**
     * Creates new form BarangMasukAddFrame
     */
    public BarangMasukAddFrame() {
        initComponents();
        awal();
    }
    
    public BarangMasukAddFrame(int id) {
        initComponents();
        awal();
    }
    
    public void awal(){
        
        sumberDanaComboBox.removeAllItems();
        sumberDanaComboBox.addItem("Hibah");
        sumberDanaComboBox.addItem("Penganggaran");
        
        try {
                Connection koneksi = Basisdata.getConnection();
                String selectSql = "SELECT * FROM pemasok ORDER BY nama_pemasok";
                Statement statement = koneksi.createStatement();
                ResultSet rs =  statement.executeQuery(selectSql);
                
                DefaultComboBoxModel m = new DefaultComboBoxModel();
                
                pemasokComboBox.removeAllItems();
                while(rs.next()){
                    m.addElement(new ComboBoxItem(
                            rs.getInt("id"),
                            rs.getString("nama_pemasok")
                    ));
                }
                pemasokComboBox.setModel(m);
                
                
                selectSql = "SELECT * FROM karyawan ORDER BY nama_karyawan";
                statement = koneksi.createStatement();
                rs =  statement.executeQuery(selectSql);
                
                m = new DefaultComboBoxModel();
                
                karyawanComboBox.removeAllItems();
                while(rs.next()){
                      m.addElement(new ComboBoxItem(
                            rs.getInt("id"),
                            rs.getString("nama_karyawan")
                    ));
                }
                karyawanComboBox.setModel(m);
                
                
                koneksi.close();
                dispose();
            } catch (SQLException ex) {
                System.err.println(ex.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        batalButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tanggalDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        sumberDanaComboBox = new javax.swing.JComboBox<>();
        pemasokComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        karyawanComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tambah Data Barang Masuk");

        jLabel2.setText("Id");

        idTextField.setEditable(false);

        jLabel3.setText("Tanggal");

        batalButton.setText("Batal");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Sumber Dana");

        jLabel5.setText("Nama Pemasok");

        sumberDanaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pemasokComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Nama Karyawan");

        karyawanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                        .addComponent(simpanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batalButton))
                    .addComponent(sumberDanaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pemasokComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(tanggalDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(karyawanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(tanggalDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sumberDanaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pemasokComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karyawanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalButton)
                    .addComponent(simpanButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        dispose();
    }//GEN-LAST:event_batalButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        String tanggal = tanggalDatePicker.getDate().toString();
        System.out.println(tanggal);
        
        String sumberDana = sumberDanaComboBox.getSelectedItem().toString();
        System.out.println(sumberDana);
        
        int pemasok_id = ((ComboBoxItem) pemasokComboBox.getSelectedItem()).getId();
        System.out.println(pemasok_id);
        
        int karyawan_id = ((ComboBoxItem) karyawanComboBox.getSelectedItem()).getId();
        System.out.println(karyawan_id);

//        if(idTextField.getText().equals("")){
//            try {
//                Connection koneksi = Basisdata.getConnection();
//                String insertSQL = "INSERT INTO karyawan SET " +
//                "nama_karyawan = '" + namaKaryawanTextField.getText() +"'," +
//                "nomor_hp = '" + nomorHpTextField.getText() +"'," +
//                "alamat = '" + alamatTextField.getText() +"'";
//
//                Statement statement = koneksi.createStatement();
//                statement.executeUpdate(insertSQL);
//                koneksi.close();
//                dispose();
//            } catch (SQLException ex) {
//                System.err.println(ex.getMessage());
//            }
//        } else {
//            try {
//                Connection koneksi = Basisdata.getConnection();
//                String updateSQL = "UPDATE karyawan SET " +
//                " nama_karyawan = '" + namaKaryawanTextField.getText() +"'," +
//                " nomor_hp = '" + nomorHpTextField.getText() +"'," +
//                " alamat = '" + alamatTextField.getText() +"'"+
//                " WHERE id=" + idTextField.getText();
//
//                Statement statement = koneksi.createStatement();
//                statement.executeUpdate(updateSQL);
//                koneksi.close();
//                dispose();
//            } catch (SQLException ex) {
//                System.err.println(ex.getMessage());
//            }
//        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangMasukAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangMasukAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangMasukAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangMasukAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangMasukAddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> karyawanComboBox;
    private javax.swing.JComboBox<String> pemasokComboBox;
    private javax.swing.JButton simpanButton;
    private javax.swing.JComboBox<String> sumberDanaComboBox;
    private com.github.lgooddatepicker.components.DatePicker tanggalDatePicker;
    // End of variables declaration//GEN-END:variables
}
